apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  annotations: 
    machineconfiguration.openshift.io/skip-validation: "true"
  labels:
    machineconfiguration.openshift.io/role: worker
  name:  99-test-file
spec:
  config:
    ignition:
      version: badversion
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,SSBhbSB2ZXJzaW9uIDEK
        path: /etc/test-file.txt
